'use client';

import React, { useState, useCallback, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useLearningStore } from '@/store/use-learning-store';
import { MindmapRenderer } from '@/components/features/topic/MindmapRenderer';
import { VideoPlayer } from '@/components/features/video/VideoPlayer';
import { AdaptivePanel } from '@/components/features/video/AdaptivePanel';
import { LearningStyleBadge } from '@/components/features/video/LearningStyleBadge';
import { StudyBuddy } from '@/components/features/video/StudyBuddy';
import { FloatingChatbot } from '@/components/features/video/FloatingChatbot';
import { Button } from '@/components/ui/button';
import { Card, CardTitle, CardDescription } from '@/components/ui/card';
import { useVideoSync } from '@/hooks/use-video-sync';
import { ArrowLeft, BookOpen, AlertCircle, RefreshCw, PanelLeftClose, PanelLeftOpen, Maximize2, Minimize2 } from 'lucide-react';
import { ROUTES } from '@/constants/routes';
import { getVideoForTopicAction } from '@/actions/video-search';

export default function TopicPage({ params }: { params: { topicSlug: string } }) {
  const router = useRouter();
  const {
    courses,
    activeCourseId,
    progress,
    markTopicCompleted,
    setActiveTopic,
    updateTopicVideoId,
    recordVideoEvent,
    recordPauseReason,
    updateTimeSpent,
  } = useLearningStore();

  const activeCourse = courses.find((c) => c.id === activeCourseId) || null;
  const currentSlug = params.topicSlug;

  // Seek state — driven by transcript timestamp clicks in AdaptivePanel
  const [seekTo, setSeekTo] = useState<number | null>(null);

  // Layout view states
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isPanelExpanded, setIsPanelExpanded] = useState(false);

  /* ── Find topic (computed, no early return) ─────────────────── */
  let activeTopic: any = null;
  if (activeCourse) {
    activeCourse.chapters.forEach((ch) => {
      const found = ch.topics.find((t) => t.slug === currentSlug);
      if (found) activeTopic = found;
    });
  }

  /* ── Progress helpers (always compute, even if guards fail) ── */
  const courseId = activeCourse?.id || '';
  const progressKey = `${courseId}:${currentSlug}`;
  const isCompleted = progress[progressKey]?.completed || false;
  const initialTime = progress[progressKey]?.videoTime || 0;

  // ALL hooks must be called unconditionally — before any return
  const syncVideoTime = useVideoSync(courseId, currentSlug);

  const handleToggleComplete = useCallback(() => {
    if (!courseId) return;
    markTopicCompleted(courseId, currentSlug, !isCompleted);
  }, [courseId, currentSlug, isCompleted, markTopicCompleted]);

  const handleNodeClick = useCallback((slug: string) => {
    setActiveTopic(slug);
    router.push(ROUTES.topic(slug));
  }, [router, setActiveTopic]);

  const handleSeekVideo = useCallback((seconds: number) => {
    setSeekTo(seconds);
    setTimeout(() => setSeekTo(null), 500);
  }, []);

  // Add this useEffect for time tracking
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (activeTopic && !isCompleted) {
      interval = setInterval(() => {
        const currentTime = localStorage.getItem(`video-time-${courseId}-${currentSlug}`);
        if (currentTime) {
          updateTimeSpent(courseId, currentSlug, parseInt(currentTime, 10));
        }
      }, 30000);
    }
    return () => clearInterval(interval);
  }, [activeTopic, isCompleted, courseId, currentSlug, updateTimeSpent]);

  const handleVideoEvent = useCallback((type: 'pause' | 'rewind' | 'skip') => {
    recordVideoEvent(type);
  }, [recordVideoEvent]);

  const handlePauseReason = useCallback((reason: 'notes' | 'confused' | 'bored') => {
    recordPauseReason(currentSlug, reason);
  }, [recordPauseReason, currentSlug]);

  const [isResolvingVideo, setIsResolvingVideo] = useState(false);

  // Check if ID was generated by the fake pseudo-random generator
  const isLikelyFakeId = useCallback((id?: string) => {
    if (!id || id.trim() === '') return true;
    if (id.length !== 11) return true;
    if (id === 'dQw4w9WgXcQ') return false; // Rickroll is real
    const fakePrefixes = [
      'dQw4w', 'W6NZf', 'rfscV', 'Tj6Hh', 'GwIo3',
      'uaCiD', 'JMUxm', 'gp5H0', 'ENrzD', 'ZVnjO',
      'M6f6J', 'P8p8K', 'L9l9M', 'N0n1O', 'Q2q3R',
    ];
    return fakePrefixes.some((p) => id.startsWith(p));
  }, []);

  // Auto-resolve video if it has no video or a known fake ID
  useEffect(() => {
    if (!activeTopic || !courseId) return;

    if (!activeTopic.videoId || isLikelyFakeId(activeTopic.videoId)) {
      let isMounted = true;
      setIsResolvingVideo(true);

      getVideoForTopicAction(activeTopic.title, activeTopic.description || '')
        .then((video) => {
          if (isMounted && video?.id) {
            updateTopicVideoId(courseId, currentSlug, video.id);
          }
        })
        .catch((err) => {
          console.warn('Auto-resolve video error:', err);
        })
        .finally(() => {
          if (isMounted) setIsResolvingVideo(false);
        });

      return () => {
        isMounted = false;
      };
    }
  }, [activeTopic?.title, activeTopic?.videoId, courseId, currentSlug, isLikelyFakeId, updateTopicVideoId]);

  const [attemptedVideoIds, setAttemptedVideoIds] = useState<Record<string, string[]>>({});

  const handleSwitchVideo = useCallback(() => {
    if (!activeTopic || !courseId) return;
    const currentVid = activeTopic.videoId;
    const prevExcluded = attemptedVideoIds[currentSlug] || [];
    const newExcluded = currentVid ? [...prevExcluded, currentVid] : prevExcluded;

    setAttemptedVideoIds((prev) => ({ ...prev, [currentSlug]: newExcluded }));
    setIsResolvingVideo(true);

    getVideoForTopicAction(activeTopic.title, activeTopic.description || '', newExcluded)
      .then((video) => {
        if (video?.id) {
          updateTopicVideoId(courseId, currentSlug, video.id);
        }
      })
      .catch((err) => console.warn('Failed to switch video:', err))
      .finally(() => setIsResolvingVideo(false));
  }, [activeTopic, courseId, currentSlug, attemptedVideoIds, updateTopicVideoId]);

  const handleVideoError = useCallback((errCode?: number) => {
    console.warn(`Video playback error (code ${errCode}) for ${currentSlug}. Auto-switching to next candidate.`);
    handleSwitchVideo();
  }, [currentSlug, handleSwitchVideo]);


  /* ── Guard: no active course ─────────────────────────────────── */
  if (!activeCourse) {
    return (
      <Card style={{ maxWidth: '500px', margin: '4rem auto', textAlign: 'center', padding: '2rem' }}>
        <AlertCircle size={36} color="#ef4444" style={{ margin: '0 auto 1rem' }} />
        <CardTitle>No Active Course</CardTitle>
        <CardDescription style={{ marginTop: '0.5rem' }}>
          Please return to the dashboard and select or generate a course first.
        </CardDescription>
        <Button onClick={() => router.push(ROUTES.dashboard)} style={{ marginTop: '1.5rem' }}>
          Go to Dashboard
        </Button>
      </Card>
    );
  }

  /* ── Guard: topic not found ──────────────────────────────────── */
  if (!activeTopic) {
    return (
      <Card style={{ maxWidth: '500px', margin: '4rem auto', textAlign: 'center', padding: '2rem' }}>
        <AlertCircle size={36} color="#ef4444" style={{ margin: '0 auto 1rem' }} />
        <CardTitle>Topic Not Found</CardTitle>
        <CardDescription style={{ marginTop: '0.5rem' }}>
          This topic doesn't exist in the current course.
        </CardDescription>
        <Button onClick={() => router.push(ROUTES.dashboard)} style={{ marginTop: '1.5rem' }}>
          Back to Dashboard
        </Button>
      </Card>
    );
  }

  /* ── Render ───────────────────────────────────────────────────── */
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', padding: '0' }} className="animate-fade-in">

      {/* Minimal Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0.75rem 1.5rem', borderBottom: '1px solid var(--cc-border, #e8e7e4)', background: 'var(--cc-surface, #ffffff)', gap: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <button
            onClick={() => router.push(ROUTES.dashboard)}
            style={{ display: 'flex', alignItems: 'center', gap: '0.45rem', background: 'var(--cc-bg, #faf9f7)', border: '1px solid var(--cc-border, #e8e7e4)', color: 'var(--cc-ink, #1a1a2e)', cursor: 'pointer', fontSize: '0.82rem', padding: '0.4rem 0.75rem', borderRadius: '7px', transition: 'all 0.15s ease', fontWeight: 500 }}
            onMouseOver={(e) => { e.currentTarget.style.background = 'rgba(79,70,229,0.06)'; }}
            onMouseOut={(e) => { e.currentTarget.style.background = 'var(--cc-bg, #faf9f7)'; }}
          >
            <ArrowLeft size={15} />
            <span>Back</span>
          </button>

          <button
            onClick={() => setIsSidebarOpen(!isSidebarOpen)}
            style={{ display: 'flex', alignItems: 'center', gap: '0.45rem', background: isSidebarOpen ? 'var(--cc-bg, #faf9f7)' : 'rgba(79,70,229,0.08)', border: '1px solid var(--cc-border, #e8e7e4)', color: isSidebarOpen ? 'var(--cc-ink-secondary, #64748b)' : 'var(--cc-accent, #4f46e5)', cursor: 'pointer', fontSize: '0.82rem', padding: '0.4rem 0.75rem', borderRadius: '7px', transition: 'all 0.15s ease', fontWeight: 500 }}
            title={isSidebarOpen ? 'Collapse chapter navigation' : 'Expand chapter navigation'}
          >
            {isSidebarOpen ? <PanelLeftClose size={15} /> : <PanelLeftOpen size={15} />}
            <span>Chapters</span>
          </button>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', minWidth: 0 }}>
          <span style={{ fontSize: '0.86rem', color: 'var(--cc-ink, #1a1a2e)', fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
            {activeTopic.title}
          </span>

          <button
            onClick={() => setIsPanelExpanded(!isPanelExpanded)}
            style={{ display: 'flex', alignItems: 'center', gap: '0.45rem', background: isPanelExpanded ? 'rgba(79,70,229,0.12)' : 'var(--cc-bg, #faf9f7)', border: '1px solid var(--cc-border, #e8e7e4)', color: isPanelExpanded ? 'var(--cc-accent, #4f46e5)' : 'var(--cc-ink-secondary, #64748b)', cursor: 'pointer', fontSize: '0.8rem', padding: '0.38rem 0.75rem', borderRadius: '7px', flexShrink: 0, transition: 'all 0.15s ease', fontWeight: 500 }}
            title={isPanelExpanded ? 'Collapse study panel to standard width' : 'Expand study panel for comfortable reading'}
          >
            {isPanelExpanded ? <Minimize2 size={13} /> : <Maximize2 size={13} />}
            <span>{isPanelExpanded ? 'Normal View' : 'Expand Notes'}</span>
          </button>
        </div>
      </div>

      {/* ── Main Layout: Video Centered, Concepts Right ────────────────────────────────── */}
      <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>

        {/* LEFT: Course navigation - Collapsible */}
        <div style={{
          width: isSidebarOpen ? '240px' : '0px',
          opacity: isSidebarOpen ? 1 : 0,
          pointerEvents: isSidebarOpen ? 'auto' : 'none',
          flexShrink: 0,
          transition: 'width 0.22s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.2s ease',
          borderRight: isSidebarOpen ? '1px solid var(--cc-border, #e8e7e4)' : 'none',
          padding: isSidebarOpen ? '1.5rem 1rem' : '0px',
          overflowY: 'auto',
          background: 'var(--cc-surface, #ffffff)',
        }}>
          <div style={{ marginBottom: '1.5rem' }}>
            <h2 style={{ fontSize: '0.92rem', fontWeight: 700, color: 'var(--cc-ink, #1a1a2e)', marginBottom: '0.25rem', fontFamily: 'var(--cc-font-display, sans-serif)' }}>{activeCourse.title}</h2>
            <p style={{ fontSize: '0.75rem', color: 'var(--cc-ink-muted, #94a3b8)' }}>{activeCourse.chapters.length} chapters</p>
          </div>
          
          {activeCourse.chapters.map((ch) => (
            <div key={ch.id} style={{ marginBottom: '1.5rem' }}>
              <p style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--cc-ink-muted, #94a3b8)', marginBottom: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                {ch.title}
              </p>
              {ch.topics.map((t) => {
                const done = progress[`${activeCourse.id}:${t.slug}`]?.completed;
                const active = t.slug === currentSlug;
                return (
                  <button
                    key={t.slug}
                    onClick={() => handleNodeClick(t.slug)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '0.5rem',
                      width: '100%', textAlign: 'left', padding: '0.6rem 0.75rem',
                      borderRadius: '8px', border: 'none',
                      background: active ? 'rgba(79,70,229,0.09)' : 'transparent',
                      color: active ? 'var(--cc-accent, #4f46e5)' : done ? 'var(--cc-ink-muted, #94a3b8)' : 'var(--cc-ink-secondary, #475569)',
                      fontWeight: active ? 600 : 400,
                      fontSize: '0.8rem', cursor: 'pointer',
                      marginBottom: '0.25rem',
                      transition: 'all 0.15s ease',
                    }}
                    onMouseOver={(e) => !active && (e.currentTarget.style.background = 'var(--cc-bg, #faf9f7)')}
                    onMouseOut={(e) => !active && (e.currentTarget.style.background = 'transparent')}
                  >
                    {done && <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#16a34a', flexShrink: 0 }} />}
                    <span style={{ flex: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{t.title}</span>
                  </button>
                );
              })}
            </div>
          ))}
        </div>

        {/* CENTER: Video player - Centered on screen */}
        <div style={{ flex: 1, minWidth: '400px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '1.5rem 2rem', background: 'rgba(0,0,0,0.3)', overflowY: 'auto' }}>
          {isResolvingVideo && (
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              marginBottom: '1rem',
              padding: '0.4rem 0.9rem',
              borderRadius: '99px',
              background: 'rgba(168,85,247,0.15)',
              border: '1px solid rgba(168,85,247,0.3)',
              color: '#d8b4fe',
              fontSize: '0.78rem',
            }}>
              <RefreshCw size={12} className="animate-spin" />
              <span>Fetching best verified educational video for this topic...</span>
            </div>
          )}

          {activeTopic.videoId ? (
            <div style={{ width: '100%', maxWidth: '900px' }}>
              <VideoPlayer
                videoId={activeTopic.videoId}
                videoTitle={activeTopic.title}
                initialTime={initialTime}
                onTimeUpdate={syncVideoTime}
                onVideoEvent={handleVideoEvent}
                onPauseReasonSubmitted={handlePauseReason}
                seekTo={seekTo}
                onVideoError={handleVideoError}
                onSwitchVideo={handleSwitchVideo}
              />
              <div style={{ marginTop: '1.5rem', padding: '0 1rem' }}>
                <h2 style={{ fontSize: '1.25rem', fontWeight: 600, color: 'white', marginBottom: '0.5rem' }}>{activeTopic.title}</h2>
                <p style={{ fontSize: '0.9rem', color: 'hsl(var(--text-muted))', lineHeight: '1.6' }}>{activeTopic.description}</p>
              </div>
            </div>
          ) : (
            <div style={{ textAlign: 'center', color: 'hsl(var(--text-muted))', padding: '3rem 2rem' }}>
              <AlertCircle size={48} style={{ margin: '0 auto 1rem', opacity: 0.4 }} />
              <p style={{ fontSize: '0.95rem', color: 'white', marginBottom: '0.5rem' }}>No video assigned to this topic</p>
              <p style={{ fontSize: '0.8rem', color: 'hsl(var(--text-muted))', marginBottom: '1.5rem' }}>
                We can automatically fetch a matching YouTube tutorial for you.
              </p>
              <Button onClick={handleVideoError} disabled={isResolvingVideo}>
                {isResolvingVideo ? 'Searching...' : 'Find Video for Topic'}
              </Button>
            </div>
          )}
        </div>

        {/* RIGHT: Concepts & Learning Panel */}
        <div style={{
          width: isPanelExpanded ? '580px' : '440px',
          minWidth: '380px',
          flexShrink: 0,
          borderLeft: '1px solid var(--cc-border, #e8e7e4)',
          padding: '0.85rem',
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column',
          background: 'var(--cc-bg, #faf9f7)',
          transition: 'width 0.22s cubic-bezier(0.4, 0, 0.2, 1)',
        }}>
          {activeTopic.videoId ? (
            <AdaptivePanel
              courseId={courseId}
              topicSlug={currentSlug}
              topicTitle={activeTopic.title}
              videoId={activeTopic.videoId}
              isCompleted={isCompleted}
              onToggleComplete={handleToggleComplete}
              onSeekVideo={handleSeekVideo}
            />
          ) : (
            <div style={{ color: 'hsl(var(--text-muted))', fontSize: '0.85rem', textAlign: 'center', marginTop: '4rem' }}>
              Learning content will appear once a video is assigned.
            </div>
          )}
        </div>

      </div>

      {/* Floating Chatbot */}
      <FloatingChatbot
        videoId={activeTopic.videoId || 'default'}
        videoTitle={activeTopic.title}
        onSeekVideo={handleSeekVideo}
      />
    </div>
  );
}
